-- Suppression pour clean start
DROP USER CYGLPI_HUB CASCADE;
DROP USER CERGY_SITE CASCADE;
DROP USER PAU_SITE CASCADE;

-- Création des schémas
CREATE USER CYGLPI_HUB IDENTIFIED BY amsterdam;
CREATE USER CERGY_SITE IDENTIFIED BY amsterdam;
CREATE USER PAU_SITE IDENTIFIED BY amsterdam;

-- Privilèges de base
GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE DATABASE LINK TO CYGLPI_HUB;
GRANT CONNECT, RESOURCE TO CERGY_SITE;
GRANT CONNECT, RESOURCE TO PAU_SITE;
GRANT CREATE DATABASE LINK, CREATE MATERIALIZED VIEW TO CERGY_SITE;
GRANT CREATE DATABASE LINK, CREATE MATERIALIZED VIEW TO PAU_SITE;
-- Quotas (important pour insérer des données)
ALTER USER CYGLPI_HUB QUOTA UNLIMITED ON USERS;
ALTER USER CERGY_SITE QUOTA UNLIMITED ON USERS;
ALTER USER PAU_SITE QUOTA UNLIMITED ON USERS;