-- Exécuter connecté en PAU_SITE (id_site par défaut = 2)
CREATE TABLE Batiment (id NUMBER PRIMARY KEY, nom VARCHAR2(255), id_site NUMBER DEFAULT 2 NOT NULL);
CREATE TABLE Salle (id NUMBER PRIMARY KEY, nom VARCHAR2(255), id_batiment NUMBER NOT NULL);
CREATE TABLE Reseau (id NUMBER PRIMARY KEY, ip_range VARCHAR2(50) NOT NULL, wan VARCHAR2(100) NOT NULL,
    vlan VARCHAR2(50), id_site NUMBER DEFAULT 2 NOT NULL);
CREATE TABLE EquipementReseau (id NUMBER PRIMARY KEY, nom VARCHAR2(255) NOT NULL, type VARCHAR2(50) NOT NULL, id_reseau NUMBER NOT NULL);
CREATE TABLE Utilisateur (id NUMBER PRIMARY KEY, nom VARCHAR2(255) NOT NULL, prenom VARCHAR2(255), login VARCHAR2(100),
    email VARCHAR2(255) NOT NULL, mot_passe_hash VARCHAR2(255) NOT NULL, est_actif NUMBER(1) DEFAULT 1,
    id_site NUMBER DEFAULT 2 NOT NULL, id_role NUMBER NOT NULL);
CREATE TABLE Materiel (id NUMBER PRIMARY KEY, nom VARCHAR2(255) NOT NULL, type VARCHAR2(50) NOT NULL,
    numero_serie VARCHAR2(255) NOT NULL, id_site NUMBER DEFAULT 2 NOT NULL, statut VARCHAR2(50) NOT NULL);
CREATE TABLE Affectation (id NUMBER PRIMARY KEY, id_utilisateur NUMBER NOT NULL, id_materiel NUMBER NOT NULL,
    date_debut TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, date_fin TIMESTAMP);
CREATE TABLE Ticket (id NUMBER PRIMARY KEY, id_technicien NUMBER, id_utilisateur NUMBER NOT NULL, id_materiel NUMBER NOT NULL,
    description CLOB NOT NULL, statut VARCHAR2(50) NOT NULL, priorite VARCHAR2(20) DEFAULT 'normale',
    date_creation TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, date_resolution TIMESTAMP);
