-- CERGY_SITE ou PAU_SITE : lien vers HUB + vues matérialisées
@/opt/GLPI_BDD/bddr/00_service_name.sql

CREATE DATABASE LINK hub_link
CONNECT TO CYGLPI_HUB IDENTIFIED BY amsterdam
USING 'localhost:1521/&pdb_service';

CREATE MATERIALIZED VIEW MV_Site
REFRESH COMPLETE ON DEMAND AS SELECT * FROM Site@hub_link;

CREATE MATERIALIZED VIEW MV_Role
REFRESH COMPLETE ON DEMAND AS SELECT * FROM Role@hub_link;

CREATE MATERIALIZED VIEW MV_Permission
REFRESH COMPLETE ON DEMAND AS SELECT * FROM Permission@hub_link;

CREATE MATERIALIZED VIEW MV_RolePermission
REFRESH COMPLETE ON DEMAND AS SELECT * FROM RolePermission@hub_link;
